name: Tag and Build Docker Image on Merge to Main

on:
  push:
    branches:
      - main

permissions:
  contents: write
  packages: write  # Potrzebne do pushowania obrazów Dockera

jobs:
  tagging_and_docker:
    needs: [Build and Test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get latest tag
        id: get_latest_tag
        run: |
          git fetch --tags
          TAG=$(git describe --tags `git rev-list --tags --max-count=1` 2>/dev/null || echo "")
          echo "Latest tag: $TAG"
          echo "LATEST_TAG=$TAG" >> $GITHUB_ENV

      - name: Calculate new tag
        id: calculate_new_tag
        run: |
          LATEST_TAG=${{ env.LATEST_TAG }}
          echo "Current tag: $LATEST_TAG"
          if [ -z "$LATEST_TAG" ]; then
            NEW_TAG="v1.0.0"
          else
            NEW_TAG=$(echo $LATEST_TAG | awk -F. -v OFS=. '{$NF += 1 ; print}')
          fi
          echo "New tag: $NEW_TAG"
          echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

      - name: Create new tag
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git tag ${{ env.NEW_TAG }}
          git push origin ${{ env.NEW_TAG }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/julia-golemo-learning-journey:${{ env.NEW_TAG }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/julia-golemo-learning-journey:${{ env.NEW_TAG }} ${{ secrets.DOCKER_USERNAME }}/julia-golemo-learning-journey:latest

      - name: Push Docker image with version tag
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/julia-golemo-learning-journey:${{ env.NEW_TAG }}

      - name: Push Docker image with 'latest' tag
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/julia-golemo-learning-journey:latest
